name: aqmeasy
channels:
  - conda-forge
dependencies:
  - python=3.12
  - crest
  - xtb
  - openbabel
  - psutil
  - pytest
  - pytest-qt
  - coverage
  - pubchempy
  - py3dmol
  - pip
  - pip:
      - aqme
      - pyside6
      - pyside6-addons
