name: Build Multi-Platform Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          install-path: $HOME/miniconda
          channels: conda-forge
          auto-update-conda: true
          auto-activate-base: false

      - name: Install Conda dependencies
        shell: bash -l {0} 
        run: |
          eval "$(conda shell.bash hook)" 
          conda create -y -n buildenv python=3.10 rdkit xtb crest aqme -c conda-forge
          conda activate buildenv

      - name: Install Pip dependencies
        shell: bash -l {0}
        run: |
          eval "$(conda shell.bash hook)"
          conda activate buildenv
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller pyside6 pubchempy

      - name: Build Executable
        shell: bash -l {0}
        run: |
          eval "$(conda shell.bash hook)"
          conda activate buildenv
          pyinstaller --onefile --noconsole --windowed main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
