name: Build Multi-Platform Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
              auto-update-conda: true
              auto-update-micromamba: true
              python-version: 3.10

      - name: Configure conda to use conda-forge
        run: |
              conda config --add channels conda-forge
              conda config --set channel_priority strict

      - name: Initialize conda
        run: conda init

      - name: Create conda environment
        run: |
              conda create -n build-env python=3.10
              conda activate build-env
              conda install -y pyinstaller pyside6 xtb crest aqme rdkit -c conda-forge
      
      - name: Install Pip Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller pyside6 pubchempy

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --windowed \
            --hidden-import=rdkit \
            --hidden-import=xtb \
            --hidden-import=crest \
            main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
