name: Build Multi-Platform Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10

      - name: Configure conda and install dependencies
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -y pyinstaller pyside6 xtb crest aqme rdkit -c conda-forge
          python -m pip install --upgrade pip setuptools wheel pubchempy

      - name: Build Executable with PyInstaller
        shell: bash -l {0}
        run: |
          pyinstaller your_script.py --onefile --noconsole --windowed \
            --hidden-import=rdkit

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
