name: Build Multi-Platform Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #windows-latest, 

    steps:
    # this works fine as expected
      - name: Checkout Code
        uses: actions/checkout@v4
# this for some reason fails but it was fine before?
      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true

      - name: Install Conda dependencies
        shell: bash 
        run: |
          eval "$(conda shell.bash hook)" # this seems to actually work properly
          conda create -y -n buildenv python=3.10
          conda activate buildenv
          conda install -y rdkit xtb crest aqme -c conda-forge
 
      - name: Install Pip Dependencies
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate buildenv
          pip install pyinstaller pyside6 pubchempy


      - name: Build Executable
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate buildenv
          pyinstaller --onefile --windowed --hidden_import=pubchempy main.py

      # Step 6: Upload Built Executable as Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
