name: Build Multi-Platform Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]#windows-latest, 

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set Up Miniconda
      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true

      # Step 3: Initialize Conda and Create Environment
      - name: Initialize Conda and Create Environment
        shell: bash 
        run: |
          conda init bash
          source ~/.bashrc
          conda create -y -n buildenv python=3.10 rdkit xtb crest aqme -c conda-forge

      # Step 4: Install Pip Dependencies (if needed)
      - name: Install Pip Dependencies
        shell: bash 
        run: |
          source ~/.bashrc
          conda activate buildenv
          pip install pyinstaller pyside6

      # Step 5: Build Executable with PyInstaller
      - name: Build Executable
        shell: bash
        run: |
          source ~/.bashrc
          conda activate buildenv
          pyinstaller --onefile --windowed main.py

      # Step 6: Upload Built Executable as Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
